service: api-to-kinesis

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-west-2
  deploymentBucket: kats-conf


functions:
  api_to_kinesis:
    handler: api-to-kinesis.handler.api_to_kinesis

